CREATE TABLE users (
   id BIGINT AUTO_INCREMENT PRIMARY KEY,
   email VARCHAR(100) NOT NULL UNIQUE,
   first_name VARCHAR(50) NOT NULL,
   last_name VARCHAR(50) NOT NULL,
   password VARCHAR(255) NOT NULL,
   role VARCHAR(20) NOT NULL,
   account_group VARCHAR(50) NOT NULL,
   date_of_birth DATE NOT NULL,
   id_number VARCHAR(20) NOT NULL UNIQUE,
   birth_number VARCHAR(20) NOT NULL UNIQUE,
   address VARCHAR(255) NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);